const state = {
    activePreset: undefined,
    options: undefined,
    version: 1,
    builtinPresets: [
        {
            name: 'Default',
            builtin: true,
            title: 'genPresetDefault',
            titleIsLoc: true,
            length: 16,
            upper: true,
            lower: true,
            digits: true,
        },
        {
            name: 'Pronounceable',
            builtin: true,
            title: 'genPresetPronounceable',
            titleIsLoc: true,
            length: 10,
            lower: true,
            upper: true,
        },
        {
            name: 'Med',
            builtin: true,
            title: 'genPresetMed',
            titleIsLoc: true,
            length: 16,
            upper: true,
            lower: true,
            digits: true,
            special: true,
            brackets: true,
            ambiguous: true,
        },
        {
            name: 'Long',
            builtin: true,
            title: 'genPresetLong',
            titleIsLoc: true,
            length: 32,
            upper: true,
            lower: true,
            digits: true,
        },
        {
            name: 'Pin4',
            builtin: true,
            title: 'genPresetPin4',
            titleIsLoc: true,
            length: 4,
            digits: true,
        },
        {
            name: 'Mac',
            builtin: true,
            title: 'genPresetMac',
            titleIsLoc: true,
            length: 17,
            upper: true,
            digits: true,
            special: true,
        },
        {
            name: 'Hash128',
            title: 'genPresetHash128',
            titleIsLoc: true,
            length: 32,
            lower: true,
            digits: true,
        },
        {
            name: 'Hash256',
            builtin: true,
            title: 'genPresetHash256',
            titleIsLoc: true,
            length: 64,
            lower: true,
            digits: true,
        },
    ],
};

export default function reducer() {
    return state;
}
